name: Deploy to GitHub Pages

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  test-deploy:
    if: github.event_name != 'push'

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Test build website
        run: pnpm build
  deploy:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
      - name: Deploy to GitHub Pages
        env:
          USE_SSH: true
        run: |
          git config --global user.email "${{ github.event.pusher.email }}"
          git config --global user.name "Pepe Fabra Valverde"
          pnpm install --frozen-lockfile
          pnpm deploy
